apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80        # Service port (inside cluster)
      targetPort: 5000 # Container port
  type: ClusterIP