services:
  frontend:
    # build: ./frontend
    image: nourrahmed/cravecart-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
   # build: ./backend
    image: nourrahmed/cravecart-backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/my-db
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
