---
- name: Deploy CraveCart App on Kubernetes
  hosts: all
  become: true

  tasks:
    - name: Ensure required packages are installed
      apt:
        name:
          - curl
          - git
        state: present
        update_cache: yes

    - name: Install k3s (lightweight Kubernetes)
      shell: curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Ensure .kube directory exists for ubuntu user
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy kubeconfig for ubuntu user
      command: cp /etc/rancher/k3s/k3s.yaml /home/ubuntu/.kube/config
      become: true

    - name: Set kubeconfig ownership
      file:
        path: /home/ubuntu/.kube/config
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Export KUBECONFIG for ubuntu user
      lineinfile:
        path: /home/ubuntu/.bashrc
        line: 'export KUBECONFIG=/home/ubuntu/.kube/config'
        state: present
        create: yes

    - name: Clone CraveCart repository
      git:
        repo: "https://github.com/NourrAhmed/CraveCart.git"
        dest: /home/ubuntu/CraveCart
        version: main
        force: yes
      become: true
      become_user: ubuntu

    - name: Deploy Backend
      command: kubectl apply -f /home/ubuntu/CraveCart/k8s/backend-deployment.yaml
      become: true

    - name: Deploy Frontend
      command: kubectl apply -f /home/ubuntu/CraveCart/k8s/frontend-deployment.yaml
      become: true

    - name: Deploy Services
      command: kubectl apply -f /home/ubuntu/CraveCart/k8s/services.yaml
      become: true

    - name: Verify Kubernetes resources
      command: kubectl get pods -o wide
      register: pod_status
      changed_when: false

    - name: Show pod status
      debug:
        var: pod_status.stdout_lines
