---
- name: Deploy CraveCart App on Kubernetes
  hosts: all
  become: yes

  tasks:
    - name: Ensure required packages are installed
      apt:
        name: [git, curl]
        state: present
        update_cache: yes

    - name: Install k3s (lightweight Kubernetes)
      shell: curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Ensure .kube directory exists for ubuntu user
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: 0755

    - name: Copy kubeconfig for ubuntu user
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu
        group: ubuntu
        mode: 0600

    - name: Set kubeconfig ownership
      file:
        path: /home/ubuntu/.kube/config
        owner: ubuntu
        group: ubuntu
        mode: 0600

    - name: Export KUBECONFIG for ubuntu user
      lineinfile:
        path: /home/ubuntu/.bashrc
        line: 'export KUBECONFIG=/home/ubuntu/.kube/config'
        insertafter: EOF

    - name: Wait for Kubernetes API to be available
      command: kubectl get nodes
      register: result
      until: result.rc == 0
      retries: 20
      delay: 10

    - name: Wait until all nodes are Ready
      command: kubectl get nodes --no-headers
      register: node_status
      until: "'Ready' in node_status.stdout"
      retries: 20
      delay: 15

    - name: Wait until kube-system pods are running
      command: kubectl get pods -n kube-system --no-headers
      register: pod_status
      until: pod_status.stdout_lines | select("search", "Running") | list | length > 3
      retries: 20
      delay: 15

    - name: Clone CraveCart repository
      ansible.builtin.git:
       repo: "https://github.com/NourrAhmed/CraveCart.git"
       dest: "/home/ubuntu/CraveCart"
       version: "main"
       depth: 1
       force: yes


    - name: Deploy Backend Deployment
      command: kubectl apply -f /home/ubuntu/CraveCart/k8s/backend/deployment.yaml --validate=false

    - name: Deploy Backend Service
      command: kubectl apply -f /home/ubuntu/CraveCart/k8s/backend/service.yaml --validate=false

    - name: Wait for Backend Pods to be Running
      shell: kubectl get pods -l app=backend -o jsonpath='{.items[*].status.phase}'
      register: backend_pods
      until: backend_pods.stdout.find("Running") != -1
      retries: 20
      delay: 15

    - name: Deploy Frontend Deployment
      command: kubectl apply -f /home/ubuntu/CraveCart/k8s/frontend/deployment.yaml --validate=false

    - name: Deploy Frontend Service
      command: kubectl apply -f /home/ubuntu/CraveCart/k8s/frontend/service.yaml --validate=false

    - name: Wait for Frontend Pods to be Running
      shell: kubectl get pods -l app=frontend -o jsonpath='{.items[*].status.phase}'
      register: frontend_pods
      until: frontend_pods.stdout.find("Running") != -1
      retries: 20
      delay: 15
