---
- name: Deploy CraveCart App on Kubernetes
  hosts: all
  become: yes

  tasks:
    - name: Ensure required packages are installed
      apt:
        name: [git, curl]
        state: present
        update_cache: yes

    - name: Install k3s (lightweight Kubernetes)
      shell: curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Ensure .kube directory exists for ubuntu user
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: 0755

    - name: Copy kubeconfig for ubuntu user
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu
        group: ubuntu
        mode: 0600

    - name: Set kubeconfig ownership
      file:
        path: /home/ubuntu/.kube/config
        owner: ubuntu
        group: ubuntu
        mode: 0600

    - name: Export KUBECONFIG for ubuntu user
      lineinfile:
        path: /home/ubuntu/.bashrc
        line: 'export KUBECONFIG=/home/ubuntu/.kube/config'
        insertafter: EOF

    - name: Wait for Kubernetes API to be available
      command: kubectl get nodes
      register: result
      until: result.rc == 0
      retries: 15
      delay: 10

    - name: Clone CraveCart repository
      git:
        repo: "https://github.com/NourrAhmed/CraveCart.git"
        dest: /home/ubuntu/CraveCart
        version: main

    - name: Deploy Backend Deployment
      command: kubectl apply -f /home/ubuntu/CraveCart/k8s/backend/deployment.yaml --validate=false

    - name: Deploy Backend Service
      command: kubectl apply -f /home/ubuntu/CraveCart/k8s/backend/service.yaml --validate=false

    - name: Deploy Frontend Deployment
      command: kubectl apply -f /home/ubuntu/CraveCart/k8s/frontend/deployment.yaml --validate=false

    - name: Deploy Frontend Service
      command: kubectl apply -f /home/ubuntu/CraveCart/k8s/frontend/service.yaml --validate=false
