---
- name: Deploy CraveCart App
  hosts: all
  become_user: ubuntu
  
  tasks:
    - name: Verify k3s is ready
      command: kubectl get nodes
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config
      retries: 5
      delay: 10

    - name: Clone CraveCart repository
      git:
        repo: "https://github.com/NourrAhmed/CraveCart.git"
        dest: "/home/ubuntu/CraveCart"
        force: yes

    - name: Deploy backend
      command: kubectl apply -f /home/ubuntu/CraveCart/k8s/backend/
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config

    - name: Deploy frontend
      command: kubectl apply -f /home/ubuntu/CraveCart/k8s/frontend/
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config

    - name: Show deployment status
      command: kubectl get pods,svc
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config
      register: status

    - debug:
        var: status.stdout_lines