name: Deploy on EC2 (Blue-Green)

on:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        working-directory: Infrastructure
        run: terraform init

      - name: Terraform Plan (remote execution)
        working-directory: Infrastructure
        run: terraform plan

      - name: Fetch Terraform outputs
        id: tf_outputs
        run: |
          curl \
            --header "Authorization: Bearer ${{ secrets.TF_API_TOKEN }}" \
            --header "Content-Type: application/vnd.api+json" \
            "https://app.terraform.io/api/v2/organizations/CraveCart/workspaces/CraveCart/current-state-version?include=outputs" \
            -o state.json

          BLUE_IP=$(jq -r '.included[] | select(.attributes.name=="blue_ip") | .attributes.value' state.json)
          GREEN_IP=$(jq -r '.included[] | select(.attributes.name=="green_ip") | .attributes.value' state.json)
          ACTIVE=$(jq -r '.included[] | select(.attributes.name=="active_env") | .attributes.value' state.json)
          PEM=$(jq -r '.included[] | select(.attributes.name=="pemFile") | .attributes.value' state.json)

          echo "BLUE_IP=$BLUE_IP" >> $GITHUB_ENV
          echo "GREEN_IP=$GREEN_IP" >> $GITHUB_ENV
          echo "ACTIVE=$ACTIVE" >> $GITHUB_ENV

          # Fix PEM newlines
          echo "$PEM" | sed 's/\\n/\n/g' > CraveCartKey.pem
          chmod 600 CraveCartKey.pem

      - name: Determine target environment
        run: |
          if [ "${ACTIVE}" = "blue" ]; then
            echo "TARGET_ENV=green" >> $GITHUB_ENV
            echo "TARGET_IP=$GREEN_IP" >> $GITHUB_ENV
          else
            echo "TARGET_ENV=blue" >> $GITHUB_ENV
            echo "TARGET_IP=$BLUE_IP" >> $GITHUB_ENV

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible jq

      - name: Create inventory file
        run: |
          mkdir -p ansible
