name: deploy on EC2

on:
    push:
        branches:
            -main

            
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: log into docker hub
              run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin

            - name: build and push frontend docker image
              run: |
               docker build -t ${{secrets.DOCKER_USERNAME}}/cravecart-frontend ./frontend
               docker push ${{secrets.DOCKER_USERNAME}}/cravecart-frontend

            - name: build and push backend docker image
              run: |
               docker build -t ${{secrets.DOCKER_USERNAME}}/cravecart-backend ./backend
               docker push ${{secrets.DOCKER_USERNAME}}/cravecart-backend

            - name: SSH into EC2 and update containers
              uses: appleboy/ssh-action@v1.0.0
              with:
                host: ${{ secrets.EC2_HOST}}
                username: ${{ secrets.EC2_USER}}
                key: ${{ secrets.EC2_SSH_KEY}}
                script: |
                 docker pull ${{ secrets.DOCKER_USERNAME }}/cravecart-backend
                 docker pull ${{ secrets.DOCKER_USERNAME }}/cravecart-frontend
                 cd /CraveCart/docker-compose
                 docker-compose down
                 docker-compose up -d
                 
