name: Deploy Infrastructure with Terraform

on: 
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Terraform Init
        run: |
          cd Infrastructure
          terraform init

      - name: Terraform Plan
        run: |
          cd Infrastructure
          terraform plan -out=tfplan 

      - name: Terraform Apply
        run: |
          cd Infrastructure 
          terraform apply -auto-approve tfplan 

      - name: Get Blue-Green outputs
        run: |
          cd Infrastructure
          terraform output -raw blue_ip > blue_ip.txt
          terraform output -raw green_ip > green_ip.txt
          terraform output -raw active_env > active_env.txt

      - name: Upload Blue-Green outputs
        uses: actions/upload-artifact@v4
        with:
          name: bg-info
          path: |
            Infrastructure/blue_ip.txt
            Infrastructure/green_ip.txt
            Infrastructure/active_env.txt
