name: Deploy Infrastructure with Terraform 

on: 
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8   

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Terraform Init
        run: cd Infrastructure && terraform init

      - name: Terraform Plan
        run: cd Infrastructure && terraform plan -out=tfplan 

      - name: Terraform Apply
        run: cd Infrastructure && terraform apply -auto-approve tfplan 

      - name: capture output
        run: |
         terraform -chdir=Infrastructure/ output -json > tf-outputs.json

      - name: Locate PEM file path
        id: pem
        run: |
          PEM_PATH=$(jq -r '.pemFile.value' tf-outputs.json)
          echo "pemFile=$PEM_PATH" >> $GITHUB_OUTPUT

      - name: Upload PEM artifact
        uses: actions/upload-artifact@v4
        with:
          name: ec2-ssh-pem
          path: Infrastructure/CraveCartKey.pem
          if-no-files-found: error
          retention-days: 1  

      - name: Upload outputs
        uses: actions/upload-artifact@v4
        with:
          name: tf-outputs
          path: tf-outputs.json
