name: Deploy Infrastructure with Terraform

on: 
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    outputs:   
      blue_ip: ${{ steps.get-outputs.outputs.blue_ip }}
      green_ip: ${{ steps.get-outputs.outputs.green_ip }}
      active_env: ${{ steps.get-outputs.outputs.active_env }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Terraform Init
        run: cd Infrastructure && terraform init

      - name: Terraform Plan
        run: cd Infrastructure && terraform plan -out=tfplan 

      - name: Terraform Apply
        run: cd Infrastructure && terraform apply -auto-approve tfplan 

      - name: Get Blue-Green outputs
        id: get-outputs   
        run: |
          cd Infrastructure
          echo "blue_ip=$(terraform output -raw blue_ip)" >> $GITHUB_OUTPUT
          echo "green_ip=$(terraform output -raw green_ip)" >> $GITHUB_OUTPUT
          echo "active_env=$(terraform output -raw active_env)" >> $GITHUB_OUTPUT
